django-budget/budget/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'budget.views',
    # Budget
    url(r'^$', 'budget_list', name='budget_list'),
    url(r'^add/$', 'budget_add', name='budget_add'),
    url(r'^edit/(?P<slug>[\w-]+)/$', 'budget_edit', name='budget_edit'),
    url(r'^delete/(?P<slug>[\w-]+)/$', 'budget_delete', name='budget_delete'),
    # Estimate
    url(r'^(?P<slug>[\w-]+)/estimate/$', 'estimate_list', name='estimate_list'),
    url(r'^(?P<slug>[\w-]+)/estimate/add/$', 'estimate_add', name='estimate_add'),
    url(r'^(?P<slug>[\w-]+)/estimate/edit/(?P<pk>\d+)/$', 'estimate_edit', name='estimate_edit'),
    url(r'^(?P<slug>[\w-]+)/estimate/delete/(?P<pk>\d+)/$', 'estimate_delete', name='estimate_delete'),
)

django-budget/config/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$',
        'base.views.index',
        name='index'),

    url(r'^i18n/',
        include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns(
    '',

    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login'),

    url(r'^logout/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^dashboard/$',
        'dashboard.views.dashboard',
        name='dashboard'),

    url(r'^setup/$',
        'base.views.setup',
        name='setup'),

    url(r'^budget/',
        include('budget.urls', namespace='budget')),

    url(r'^category/',
        include('category.urls', namespace='category')),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^transaction/',
        include('transaction.urls', namespace='transaction')),

    url(r'^summary/',
        include('summary.urls', namespace='summary')),
)

django-budget/budget/models.py
from __future__ import unicode_literals

from datetime import date
from decimal import Decimal

from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from base.models import ActiveManager, StandardMetadata
from category.models import Category
from transaction.models import Transaction


class BudgetLatestManager(ActiveManager):
    def most_current_for_date(self, date):
        return super(BudgetLatestManager, self).get_query_set().filter(start_date__lte=date).latest('start_date')


@python_2_unicode_compatible
class Budget(StandardMetadata):
    name = models.CharField(_('Name'), max_length=100)
    slug = models.SlugField(_('Slug'), unique=True)
    start_date = models.DateField(_('Start Date'),
                                  default=date.today,
                                  db_index=True)

    objects = models.Manager()
    active = BudgetLatestManager()

    def __str__(self):
        return self.name

    def actual_total(self, start_date, end_date):
        actual_total = Decimal('0.0')

        for estimate in self.estimates.exclude(is_deleted=True):
            actual_amount = estimate.actual_amount(start_date, end_date)
            actual_total += actual_amount

        return actual_total

    def estimates_and_transactions(self, start_date, end_date):
        estimates_and_transactions = []
        actual_total = Decimal('0.0')

        for estimate in self.estimates.exclude(is_deleted=True):
            actual_amount = estimate.actual_amount(start_date, end_date)
            actual_total += actual_amount
            estimates_and_transactions.append({
                'estimate': estimate,
                'transactions': estimate.actual_transactions(start_date, end_date),
                'actual_amount': actual_amount,
            })

        return (estimates_and_transactions, actual_total)

    def monthly_estimated_total(self):
        total = Decimal('0.0')
        for estimate in self.estimates.exclude(is_deleted=True):
            total += estimate.amount
        return total

    def yearly_estimated_total(self):
        return self.monthly_estimated_total() * 12

    class Meta:
        verbose_name = _('Budget')
        verbose_name_plural = _('Budgets')


@python_2_unicode_compatible
class BudgetEstimate(StandardMetadata):
    budget = models.ForeignKey(Budget,
                               related_name='estimates',
                               verbose_name=_('Budget'),
                               limit_choices_to={'is_deleted': False})
    category = models.ForeignKey(Category,
                                 related_name='estimates',
                                 verbose_name=_('Category'),
                                 limit_choices_to={'is_deleted': False})
    amount = models.DecimalField(_('Amount'), max_digits=11, decimal_places=2)

    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return '%s - %.02f' % (self.category.name, self.amount)

    def actual_transactions(self, start_date, end_date):
        return Transaction.expenses.filter(category=self.category,
                                           date__range=(start_date, end_date)
                                           ).order_by('date')

    def actual_amount(self, start_date, end_date):
        return Transaction.expenses.filter(category=self.category,
                                           date__range=(start_date, end_date)
                                           ).aggregate(Sum('amount'))['amount__sum'] or Decimal('0.0')

    def yearly_estimated_amount(self):
        return self.amount * 12

    class Meta:
        verbose_name = _('Budget estimate')
        verbose_name_plural = _('Budget estimates')

django-budget/budget/forms.py
from __future__ import unicode_literals

from django import forms
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from crispy_forms.bootstrap import PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout

from base.forms import DatePickerInput
from .models import Budget, BudgetEstimate


class BudgetForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BudgetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Field('name'),
            PrependedText('start_date',
                          '<i class="glyphicon glyphicon-calendar"></i>'))

    def save(self):
        if not self.instance.slug:
            self.instance.slug = slugify(self.cleaned_data['name'])
        return super(BudgetForm, self).save()

    class Meta:
        model = Budget
        fields = ('name', 'start_date')
        widgets = {'start_date': DatePickerInput()}


class BudgetEstimateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BudgetEstimateForm, self).__init__(*args, **kwargs)
        self.fields['amount'].localize = True

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Field('category'),
            PrependedText('amount', _('$')))

    class Meta:
        model = BudgetEstimate
        fields = ('category', 'amount')

django-budget/budget/views.py
from __future__ import unicode_literals

from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from django.utils.translation import ugettext_lazy as _

from braces.views import LoginRequiredMixin

from .forms import BudgetEstimateForm, BudgetForm
from .models import Budget, BudgetEstimate


class BudgetListView(LoginRequiredMixin, ListView):
    model = Budget
    template_name = 'budget/list.html'
    context_object_name = 'budgets'
    queryset = Budget.active.all()
    paginate_by = 10


budget_list = BudgetListView.as_view()


class BudgetCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Budget
    template_name = 'budget/add.html'
    form_class = BudgetForm
    success_url = reverse_lazy('budget:budget_list')
    success_message = _('Budget %(name)s was created successfuly!')

budget_add = BudgetCreateView.as_view()


class BudgetUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Budget
    template_name = 'budget/edit.html'
    form_class = BudgetForm
    success_url = reverse_lazy('budget:budget_list')
    success_message = _('Budget %(name)s was updated successfuly!')

budget_edit = BudgetUpdateView.as_view()


class BudgetDeleteView(LoginRequiredMixin, DeleteView):
    model = Budget
    template_name = "budget/delete.html"
    success_url = reverse_lazy('budget:budget_list')

budget_delete = BudgetDeleteView.as_view()


class BudgetEstimateListView(LoginRequiredMixin, ListView):
    model = BudgetEstimate
    template_name = "estimate/list.html"
    context_object_name = 'estimates'
    queryset = BudgetEstimate.active.select_related().all()
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super(BudgetEstimateListView, self).get_context_data(*args, **kwargs)
        budget_slug = self.kwargs.get('slug', None)
        budget = get_object_or_404(Budget.active.all(), slug=budget_slug)
        context['budget'] = budget
        return context

estimate_list = BudgetEstimateListView.as_view()


class BudgetEstimateCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = BudgetEstimate
    template_name = "estimate/add.html"
    form_class = BudgetEstimateForm
    success_url = reverse_lazy('budget:budget_list')
    success_message = _('Estimate was created successfuly!')

    def form_valid(self, form):
        budget_slug = self.kwargs.get('slug', None)
        budget = get_object_or_404(Budget.active.all(), slug=budget_slug)
        form.save(commit=False)
        form.instance.budget = budget
        return super(BudgetEstimateCreateView, self).form_valid(form)

estimate_add = BudgetEstimateCreateView.as_view()


class BudgetEstimateUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = BudgetEstimate
    template_name = 'estimate/edit.html'
    form_class = BudgetEstimateForm
    success_url = reverse_lazy('budget:budget_list')
    success_message = _('Estimate was updated successfuly!')
    context_object_name = 'estimate'

estimate_edit = BudgetEstimateUpdateView.as_view()


class BudgetEstimateDeleteView(LoginRequiredMixin, DeleteView):
    model = BudgetEstimate
    template_name = "estimate/delete.html"
    success_url = reverse_lazy('budget:budget_list')
    context_object_name = 'estimate'

estimate_delete = BudgetEstimateDeleteView.as_view()

django-budget/budget/templates/budget/add.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block extra_css %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/datepicker3.css' %}">
{% endblock extra_css %}

{% block title %}{% trans "Add A Budget" %}{% endblock title %}

{% block content %}

<h2>{% trans "Add A Budget" %}</h2>

<form method="post" action="." class="col-md-6">
    {% csrf_token %}

    {% crispy form %}

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        <a href="{% url 'budget:budget_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
    </div>
</form>

{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/datepicker.js' %}"></script>
{% endblock extra_js %}

django-budget/budget/templates/budget/delete.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Delete Budget" %}{% endblock title %}

{% block content %}

<h2>{% trans "Delete Budget" %}</h2>

<p>
    {% blocktrans with name=budget.name %}
    Are you sure you want to delete "{{ name }}"?
    {% endblocktrans %}
</p>

<form method="post" action=".">
    {% csrf_token %}

    <div class="form-actions">
        <a href="{% url 'budget:budget_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
        <button type="submit" class="btn btn-danger">{% trans "Yes, I'm sure" %}</button>
    </div>

</form>

{% endblock content %}

django-budget/budget/templates/budget/edit.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extra_css %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/datepicker3.css' %}">
{% endblock extra_css %}

{% block title %}{% trans "Edit Budget" %}{% endblock title %}

{% block content %}

<h2>{% trans "Edit Budget" %}</h2>

<div class="row">
    <form method="post" action="." class="col-md-6">
        {% csrf_token %}

        {% crispy form %}

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url 'budget:budget_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
        </div>
    </form>
</div>

<br />

<p>
    {% trans "You can also" %}
    <a href="{% url 'budget:budget_delete' budget.slug %}">{% trans "delete" %}</a>
    {% trans "this budget." %}
</p>

{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/datepicker.js' %}"></script>
{% endblock extra_js %}

django-budget/budget/templates/budget/list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Budget List" %}{% endblock title %}

{% block content %}

<p>
    <a class="btn btn-success" href="{% url 'budget:budget_add' %}">
        <i class="glyphicon glyphicon-plus"></i>
        {% trans "New Budget" %}
    </a>
</p>

<div id="budgets" class="panel panel-primary">
      <div class="panel-heading">
            <h3 class="panel-title">{% trans "Budget List" %}</h3>
      </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="sort" data-sort="id">#</th>
                <th class="sort" data-sort="name">{% trans "Name" %}</th>
                <th class="sort" data-sort="date">{% trans "Start Date" %}</th>
                <th class="col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">
                            <i class="glyphicon glyphicon-search"></i>
                        </span>
                        <input type="text" class="search form-control" placeholder="{% trans "Search..." %}" />
                    </div>
                </th>
            </tr>
        </thead>
        <tbody class="list">
            {% if budgets %}
                {% for budget in budgets %}
                    <tr>
                        <td class="id">{{ budget.id }}</td>
                        <td class="name">{{ budget.name }}</td>
                        <td class="date">{{ budget.start_date|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>
                            <a href="{% url 'budget:budget_edit' budget.slug %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
                            <a href="{% url 'budget:budget_delete' budget.slug %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
                            <a class="btn btn-success btn-sm" href="{% url 'budget:estimate_list' budget.slug %}">{% trans "View/Add Estimates" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">{% trans "No budgets found." %}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

{% include 'pagination.html' %}

{% endblock %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}js/list.min.js"></script>
    <script type="text/javascript">
        var options = {
            valueNames: ['id', 'name', 'date']
        };

        var budgetList = new List('budgets', options);
    </script>
{% endblock extra_js %}