django-budget/budget/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'budget.views',
    # Budget
    url(r'^$', 'budget_list', name='budget_list'),
    url(r'^add/$', 'budget_add', name='budget_add'),
    url(r'^edit/(?P<slug>[\w-]+)/$', 'budget_edit', name='budget_edit'),
    url(r'^delete/(?P<slug>[\w-]+)/$', 'budget_delete', name='budget_delete'),
    # Estimate
    url(r'^(?P<slug>[\w-]+)/estimate/$', 'estimate_list', name='estimate_list'),
    url(r'^(?P<slug>[\w-]+)/estimate/add/$', 'estimate_add', name='estimate_add'),
    url(r'^(?P<slug>[\w-]+)/estimate/edit/(?P<pk>\d+)/$', 'estimate_edit', name='estimate_edit'),
    url(r'^(?P<slug>[\w-]+)/estimate/delete/(?P<pk>\d+)/$', 'estimate_delete', name='estimate_delete'),
)

django-budget/category/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'category.views',
    url(r'^$', 'category_list', name='category_list'),
    url(r'^add/$', 'category_add', name='category_add'),
    url(r'^edit/(?P<slug>[\w_-]+)/$', 'category_edit', name='category_edit'),
    url(r'^delete/(?P<slug>[\w_-]+)/$', 'category_delete', name='category_delete'),
)

django-budget/config/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$',
        'base.views.index',
        name='index'),

    url(r'^i18n/',
        include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns(
    '',

    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login'),

    url(r'^logout/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^dashboard/$',
        'dashboard.views.dashboard',
        name='dashboard'),

    url(r'^setup/$',
        'base.views.setup',
        name='setup'),

    url(r'^budget/',
        include('budget.urls', namespace='budget')),

    url(r'^category/',
        include('category.urls', namespace='category')),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^transaction/',
        include('transaction.urls', namespace='transaction')),

    url(r'^summary/',
        include('summary.urls', namespace='summary')),
)

django-budget/transaction/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'transaction.views',
    url(r'^$', 'transaction_list', name='transaction_list'),
    url(r'^add/$', 'transaction_add', name='transaction_add'),
    url(r'^edit/(?P<pk>\d+)/$', 'transaction_edit', name='transaction_edit'),
    url(r'^delete/(?P<pk>\d+)/$', 'transaction_delete', name='transaction_delete'),
)

django-budget/dashboard/views.py
from __future__ import unicode_literals

from datetime import date, timedelta
from decimal import InvalidOperation

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils import timezone

from budget.models import Budget
from transaction.models import Transaction


@login_required
def dashboard(request):
    try:
        budget = Budget.active.most_current_for_date(timezone.now())

    except Budget.DoesNotExist:
        return redirect('setup')

    latest_expenses = Transaction.expenses.get_latest()
    latest_incomes = Transaction.incomes.get_latest()

    now = timezone.now()
    start_date = date(now.year, now.month, 1)
    end_year, end_month = now.year, now.month + 1

    end_date = date(end_year, end_month + 1, 1) - timedelta(days=1)

    estimated_amount = budget.monthly_estimated_total()
    amount_used = budget.actual_total(start_date, end_date)

    try:
        progress_bar_percent = min(100, amount_used / estimated_amount * 100)

    except InvalidOperation:
        progress_bar_percent = 0

    ctx = {'budget': budget,
           'estimated_amount': estimated_amount,
           'amount_used': amount_used,
           'latest_incomes': latest_incomes,
           'latest_expenses': latest_expenses,
           'progress_bar_percent': progress_bar_percent}

    return render(request, 'dashboard.html', ctx)

django-budget/dashboard/templates/dashboard.html
{% extends "base.html" %}

{% load i18n %}
{% load budget_tags %}

{% block title %}{% trans "Dashboard" %}{% endblock title %}

{% block content %}

<h1>{% trans "Dashboard" %}</h1>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Latest Expenses" %}</h3>
            </div>

            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>{% trans "Notes" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th class="numeric">{% trans "Amount" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% if latest_expenses %}
                        {% for expense in latest_expenses %}
                            <tr>
                                <td>{{ expense.notes }}</td>
                                <td>{{ expense.date|date:"SHORT_DATE_FORMAT" }}</td>
                                <td class="numeric">
                                    <a href="{% url 'transaction:transaction_edit' expense.id %}">
                                        {% trans "$" %} {{ expense.amount|stringformat:".02f" }}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">{% trans "No recent expenses found." %}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Latest Incomes" %}</h3>
            </div>

            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>{% trans "Notes" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th class="numeric">{% trans "Amount" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% if latest_incomes %}
                        {% for income in latest_incomes %}
                            <tr>
                                <td>{{ income.notes }}</td>
                                <td>{{ income.date|date:"SHORT_DATE_FORMAT" }}</td>
                                <td class="numeric">
                                    <a href="{% url 'transaction:transaction_edit' income.id %}">{% trans "$" %} {{ income.amount|stringformat:".02f" }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">{% trans "No recent incomes found." %}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<p>
    <a class="btn btn-success" href="{% url 'transaction:transaction_add' %}"><i class="glyphicon glyphicon-plus"></i> {% trans "New Transaction" %}</a>
</p>

<br />

<h3>{% trans "This Month's Usage" %}</h3>

<div class="progress progress-striped">
    <div class="progress-bar progress-bar-{% colorize_amount estimated_amount amount_used %}" style="width: {{ progress_bar_percent|stringformat:"d" }}%;">&nbsp;</div>
</div>

<p class="lead">
    {% blocktrans with amount=amount_used|stringformat:".02f" estimate=estimated_amount|stringformat:".02f"%}
        $ {{ amount }} out of $ {{ estimate }}.
    {% endblocktrans %}
</p>

{% endblock content %}

django-budget/dashboard/templates/setup.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Setup" %}{% endblock title %}

{% block content %}

<h1>{% trans "Setup" %}</h1>

<p>
    {% blocktrans %}
    Before you can start using this application, we need to put together
    a budget. Three quick steps and you'll be ready to start using
    everything. You can come back to this screen at any time to make
    changes or add new items.
    {% endblocktrans %}
</p>

<h3>{% trans "Step 1. Create Categories" %}</h3>

<p>
    {% blocktrans %}
    Before we can put together the budget, we need categories to tie
    the incomes/expenses you enter to the line items in your budget.
    Nothing more than a descriptive name is required for each category,
    though you may want to err on the side of being a little broad
    when naming the category.
    {% endblocktrans %}
</p>

<p>
    <a class="btn btn-primary" href="{% url 'category:category_list' %}">{% trans "View/Add Categories" %}</a>
</p>

<h3>{% trans "Step 2. Create A Budget" %}</h3>

<p>
    {% blocktrans %}
        Once you have a couple categories in place, we can create a budget.
        Again, not a lot of information is needed here, just a name and when
        you'd like the budget to start being used. This application always
        tries to use the most recent budget for whatever date is chosen.
    {% endblocktrans %}
</p>

<p>
    <a class="btn btn-primary btn-success" href="{% url 'budget:budget_list' %}">{% trans "View/Add Budgets" %}</a>
</p>

<h3>{% trans "Step 3. Create Budget Estimates" %}</h3>

<p>
    {% blocktrans %}
        The last step is to create the line items that make up a budget. To do
        this, we'll tie together the budget the estimate applies to, the
        category it covers and how much you'd like to allocate to that type of
        expense per month.
    {% endblocktrans %}
</p>

<p>
    {% blocktrans %}
        To view/add estimates, go into the Budget list and click the
        "View/Add Estimates" link on the budget you'd like to work with.
    {% endblocktrans %}
</p>

<p>
    <a class="btn btn-info" href="{% url 'budget:budget_list' %}">{% trans "View/Add Estimates Within A Budget" %}</a>
</p>

<h3>{% trans "Step 4. All Set!" %}</h3>

<p>
    {% blocktrans %}
        You can now use the rest of the application. You'll probably want to
        start with the "Transactions" area to add some incomes/expenses, then
        go to the "Dashboard" for an overview or "Summaries" for more detail.
    {% endblocktrans %}
</p>

{% endblock content %}