django-budget/budget/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'budget.views',
    # Budget
    url(r'^$', 'budget_list', name='budget_list'),
    url(r'^add/$', 'budget_add', name='budget_add'),
    url(r'^edit/(?P<slug>[\w-]+)/$', 'budget_edit', name='budget_edit'),
    url(r'^delete/(?P<slug>[\w-]+)/$', 'budget_delete', name='budget_delete'),
    # Estimate
    url(r'^(?P<slug>[\w-]+)/estimate/$', 'estimate_list', name='estimate_list'),
    url(r'^(?P<slug>[\w-]+)/estimate/add/$', 'estimate_add', name='estimate_add'),
    url(r'^(?P<slug>[\w-]+)/estimate/edit/(?P<pk>\d+)/$', 'estimate_edit', name='estimate_edit'),
    url(r'^(?P<slug>[\w-]+)/estimate/delete/(?P<pk>\d+)/$', 'estimate_delete', name='estimate_delete'),
)

django-budget/config/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$',
        'base.views.index',
        name='index'),

    url(r'^i18n/',
        include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns(
    '',

    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login'),

    url(r'^logout/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^dashboard/$',
        'dashboard.views.dashboard',
        name='dashboard'),

    url(r'^setup/$',
        'base.views.setup',
        name='setup'),

    url(r'^budget/',
        include('budget.urls', namespace='budget')),

    url(r'^category/',
        include('category.urls', namespace='category')),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^transaction/',
        include('transaction.urls', namespace='transaction')),

    url(r'^summary/',
        include('summary.urls', namespace='summary')),
)

django-budget/transaction/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'transaction.views',
    url(r'^$', 'transaction_list', name='transaction_list'),
    url(r'^add/$', 'transaction_add', name='transaction_add'),
    url(r'^edit/(?P<pk>\d+)/$', 'transaction_edit', name='transaction_edit'),
    url(r'^delete/(?P<pk>\d+)/$', 'transaction_delete', name='transaction_delete'),
)

django-budget/transaction/models.py
from __future__ import unicode_literals

from datetime import date

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from base.models import ActiveManager, StandardMetadata
from category.models import Category


class TransactionLatestManager(ActiveManager):
    def get_latest(self, limit=10):
        return self.get_query_set().order_by('-date', '-created')[0:limit]


class TransactionIncomeManager(TransactionLatestManager):
    def get_query_set(self):
        return super(TransactionIncomeManager, self).get_query_set().filter(transaction_type=Transaction.INCOME)


class TransactionExpenseManager(TransactionLatestManager):
    def get_query_set(self):
        return super(TransactionExpenseManager, self).get_query_set().filter(transaction_type=Transaction.EXPENSE)


class TransactionByMonthManager(ActiveManager):
    def get_query_set(self):
        return super(TransactionByMonthManager, self).get_query_set().dates('date', 'month')


@python_2_unicode_compatible
class Transaction(StandardMetadata):
    EXPENSE = 'expense'
    INCOME = 'income'
    TRANSACTION_TYPES = (
        (INCOME, _('Income')),
        (EXPENSE, _('Expense')))

    transaction_type = models.CharField(_('Transaction Type'),
                                        choices=TRANSACTION_TYPES,
                                        max_length=32,
                                        default=EXPENSE,
                                        db_index=True)
    category = models.ForeignKey(Category,
                                 verbose_name=_('Category'),
                                 limit_choices_to={'is_deleted': False})
    notes = models.TextField(_('Notes'), max_length=255, blank=True)
    amount = models.DecimalField(_('Amount'), max_digits=11, decimal_places=2)
    date = models.DateField(_('Date'), db_index=True, default=date.today)

    objects = models.Manager()
    active = ActiveManager()
    latest = TransactionLatestManager()
    incomes = TransactionIncomeManager()
    expenses = TransactionExpenseManager()
    months = TransactionByMonthManager()

    def __str__(self):
        return '%s (%s) - %.02f' % (self.notes,
                                    self.get_transaction_type_display(),
                                    self.amount)

    class Meta:
        verbose_name = _('Transaction')
        verbose_name_plural = _('Transactions')

django-budget/transaction/forms.py
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from crispy_forms.bootstrap import PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout

from base.forms import DatePickerInput
from .models import Transaction


class TransactionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-6'
        self.helper.layout = Layout(
            Field('transaction_type'),
            Field('category'),
            PrependedText('amount', _('$')),
            PrependedText('date', '<i class="glyphicon glyphicon-calendar"></i>'),
            Field('notes'))

    class Meta:
        model = Transaction
        widgets = {'date': DatePickerInput()}

django-budget/transaction/views.py
from __future__ import unicode_literals

from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from django.utils.translation import ugettext_lazy as _

from braces.views import LoginRequiredMixin

from .forms import TransactionForm
from .models import Transaction


class TransactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transaction/list.html'
    context_object_name = 'transactions'
    queryset = Transaction.active.all().select_related()
    paginate_by = 10

transaction_list = TransactionListView.as_view()


class TransactionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'transaction/add.html'
    success_url = reverse_lazy('transaction:transaction_list')
    success_message = _('Transaction was created successfuly!')

transaction_add = TransactionCreateView.as_view()


class TransactionUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Transaction
    template_name = 'transaction/edit.html'
    form_class = TransactionForm
    success_url = reverse_lazy('transaction:transaction_list')
    success_message = _('Transaction was updated successfuly!')

transaction_edit = TransactionUpdateView.as_view()


class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    template_name = 'transaction/delete.html'
    success_url = reverse_lazy('transaction:transaction_list')

transaction_delete = TransactionDeleteView.as_view()

django-budget/transaction/templates/transaction/add.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
   <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/datepicker3.css">
{% endblock extra_css %}

{% block title %}{% trans "Add A Transaction" %}{% endblock title %}

{% block content %}

<h2>{% trans "Add A Transaction" %}</h2>

<form method="post" action="." class="form-horizontal">
    {% csrf_token %}

    {% crispy form %}

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url 'transaction:transaction_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
        </div>
    </div>
</form>

{% endblock content %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    <script src="{{ STATIC_URL }}js/datepicker.js"></script>
{% endblock extra_js %}

django-budget/transaction/templates/transaction/delete.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Delete Transaction" %}{% endblock title %}

{% block content %}

<h2>{% trans "Delete Transaction" %}</h2>

<p>
    {% blocktrans %}
    Are you sure you want to delete "{{ transaction }}"?
    {% endblocktrans %}
</p>

<form method="post" action=".">
    {% csrf_token %}

    <div class="form-actions">
        <a href="{% url 'transaction:transaction_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
        <button type="submit" class="btn btn-danger">{% trans "Yes, I'm sure" %}</button>
    </div>
</form>

{% endblock content %}

django-budget/transaction/templates/transaction/edit.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
   <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/datepicker3.css">
{% endblock extra_css %}

{% block title %}{% trans "Edit Transaction" %}{% endblock title %}

{% block content %}

<h2>{% trans "Edit Transaction" %}</h2>

<form method="post" action="." class="form-horizontal">
    {% csrf_token %}

    {% crispy form %}

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url 'transaction:transaction_list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
        </div>
    </div>
</form>

<br />

<p>
    {% trans "You can also" %}
    <a href="{% url 'transaction:transaction_delete' transaction.id %}">{% trans "delete" %}</a>
    {% trans "this transaction." %}
</p>

{% endblock content %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    <script src="{{ STATIC_URL }}js/datepicker.js"></script>
{% endblock extra_js %}

django-budget/transaction/templates/transaction/list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Transaction List" %}{% endblock title %}

{% block content %}

<p>
    <a class="btn btn-success" href="{% url 'transaction:transaction_add' %}">
        <i class="glyphicon glyphicon-plus" class="glyphicon glyphicon-plus"></i>
        {% trans "New Transaction" %}
    </a>
</p>

<div id="transactions" class="panel panel-primary">
      <div class="panel-heading">
            <h3 class="panel-title">{% trans "Transaction List" %}</h3>
      </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="sort" data-sort="id">#</th>
                <th class="sort" data-sort="note">{% trans "Notes" %}</th>
                <th class="sort" data-sort="type">{% trans "Type" %}</th>
                <th class="sort" data-sort="date">{% trans "Date" %}</th>
                <th class="sort" data-sort="category">{% trans "Category" %}</th>
                <th class="numeric sort" data-sort="amount">{% trans "Amount" %}</th>
                <th>
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">
                            <i class="glyphicon glyphicon-search"></i>
                        </span>
                        <input type="text" class="search form-control" placeholder="{% trans "Search..." %}" />
                    </div>
                </th>
            </tr>
        </thead>
        <tbody class="list">
            {% if transactions %}
                {% for transaction in transactions %}
                    <tr>
                        <td class="id">{{ transaction.id }}</td>
                        <td class="note">{{ transaction.notes }}</td>
                        <td class="type">{{ transaction.get_transaction_type_display }}</td>
                        <td class="date">{{ transaction.date|date:"SHORT_DATE_FORMAT" }}</td>
                        <td class="category">{{ transaction.category.name }}</td>
                        <td class="numeric amount">
                            {% blocktrans with amount=transaction.amount|stringformat:".02f" %}
                               $ {{ amount }}
                            {% endblocktrans %}
                        <td>
                            <a href="{% url 'transaction:transaction_edit' transaction.id %}" class="btn btn-default btn-sm">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                            <a href="{% url 'transaction:transaction_delete' transaction.id %}" class="btn btn-default btn-sm">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">{% trans "No transactions found." %}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

{% include 'pagination.html' %}

{% endblock content %}

{% block extra_js %}
   <script src="{{ STATIC_URL }}/js/list.min.js"></script>
    <script type="text/javascript">
        var options = {
            valueNames: ['id', 'note', 'type', 'date', 'category', 'amount']
        };

        var transactionList = new List('transactions', options);
    </script>
{% endblock extra_js %}